# Generated by Django 5.1.1 on 2024-09-13 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название",
                        max_length=300,
                        verbose_name="Название объекта сети",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("завод", "завод"),
                            ("розница", "розничная сеть"),
                            ("ИП", "индивидуальный предприниматель"),
                        ],
                        default="завод",
                        help_text="Укажите тип звена сети",
                        verbose_name="Тип звена сети",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[(0, "0"), (1, "1"), (2, "2")],
                        default=0,
                        help_text="Укажите уровень в иерархии поставок",
                        verbose_name="Уровень в иерархии поставок",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Укажите электронную почту",
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Укажите страну",
                        max_length=100,
                        null=True,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Укажите город",
                        max_length=100,
                        null=True,
                        verbose_name="Город",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        help_text="Укажите улицу",
                        max_length=100,
                        null=True,
                        verbose_name="Улица",
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True,
                        help_text="Укажите номер дома",
                        max_length=15,
                        null=True,
                        verbose_name="Номер дома",
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                        verbose_name="Задолженность перед поставщиком",
                    ),
                ),
                (
                    "date_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="electronicplatform.platformunit",
                        verbose_name="Cсылка на поставщика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект сети",
                "verbose_name_plural": "Объекты сети",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название",
                        max_length=150,
                        verbose_name="название",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="Укажите модель",
                        max_length=150,
                        null=True,
                        verbose_name="модель",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату выхода продукта на рынок",
                        null=True,
                        verbose_name="дата выхода продукта на рынок",
                    ),
                ),
                (
                    "network_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electronicplatform.platformunit",
                        verbose_name="Объект сети",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
